# Generated by Django 3.2.2 on 2021-05-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
