# Generated by Django 3.2.2 on 2021-05-13 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0002_auto_20210513_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picApp.category'),
        ),
    ]
