# Generated by Django 3.2.2 on 2021-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0004_alter_photo_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='picLargeHeight',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photo',
            name='picLargeWidth',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
