# Generated by Django 3.2.2 on 2021-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0014_alter_blog_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='tag',
            field=models.CharField(max_length=10),
        ),
    ]
